import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { PiScope,PiScopeLogic } from "pi-scope.slint";
export enum Page { Home, PiScope,About }


export {PiScopeLogic}

export component MainWindow inherits Window {

    // Aktuelle Seite (simuliert)
    in-out property <Page> current_page: Home;
    callback ConnectPiScopeHost(string);
    in-out property <[string]> known_pi_scopes;
    
    HorizontalBox {
        // Linke Navigation
        VerticalBox {
            spacing: 10px;
            padding: 10px;
            width: 150px;
            //background: #ddd;

            Button {
                text: "Home";
                clicked => {
                    root.current_page = Page.Home;
                }
            }

            Button {
                text: "PiScope";
                clicked => {
                    root.current_page = Page.PiScope;
                }
            }

            Button {
                text: "About";
                clicked => {
                    root.current_page = Page.About;
                }
            }
        }

        // Rechte Inhaltsfläche (aktuelle Komponente)
        Rectangle {
            min-width: 200px;
            padding: 20px;
            if current_page == Page.Home: Text {
                text: "Home";
            }
            if current_page == Page.PiScope: PiScope {
                known_pi_scopes: known_pi_scopes;
            }
            if current_page == Page.About:Text {
                text: "About";
            }
        }
    }
}
